# This is a basic workflow to help you get started with Actions
# Copied from https://github.com/Feeding-Thailand/thaifoodbank/blob/master/.github/workflows/CI.yml

name: genblogs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: [gen]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Install node_modules
    - name: Install Dependencies
      run: npx yarn
      
    # Build sites
    - name: Build Sites
      run: npx yarn build
    
    # Deploy to firebase
    - name: Deploy Firebase Hosting
      uses: lowply/deploy-firebase@v0.0.5
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: blog-raw
